#include <iostream>

// 7_6_exception_safety.cpp

void f() noexcept // since C++11, f does not throw exceptions
{
    
}